import React from 'react';
import { ChevronLeft, Shield, Lock, FileText, AlertTriangle, CheckCircle2, Globe, CreditCard, Star, Users, Activity, Target, BookOpen, HeadphonesIcon } from 'lucide-react';

interface InfoPageProps {
  title: string;
  onBack: () => void;
}

export default function InfoPage({ title, onBack }: InfoPageProps) {
  const renderContent = () => {
    switch (title) {
      case 'Help Center':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Welcome to the ONYX OPTION Help Center. How can we assist you today?</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <BookOpen className="text-blue-500 mb-4" size={32} />
                <h3 className="text-xl font-bold mb-2 text-white">Getting Started</h3>
                <p className="text-gray-400">Learn the basics of setting up your account and making your first trade.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <CreditCard className="text-emerald-500 mb-4" size={32} />
                <h3 className="text-xl font-bold mb-2 text-white">Deposits & Withdrawals</h3>
                <p className="text-gray-400">Everything you need to know about funding your account and withdrawing profits.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <Target className="text-rose-500 mb-4" size={32} />
                <h3 className="text-xl font-bold mb-2 text-white">Trading Strategies</h3>
                <p className="text-gray-400">Advanced techniques and strategies to improve your trading performance.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <Lock className="text-indigo-500 mb-4" size={32} />
                <h3 className="text-xl font-bold mb-2 text-white">Account Security</h3>
                <p className="text-gray-400">Best practices for keeping your account and funds secure.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <Activity className="text-amber-500 mb-4" size={32} />
                <h3 className="text-xl font-bold mb-2 text-white">Technical Analysis</h3>
                <p className="text-gray-400">Master chart patterns, indicators, and trend analysis.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <Users className="text-purple-500 mb-4" size={32} />
                <h3 className="text-xl font-bold mb-2 text-white">Community & Social Trading</h3>
                <p className="text-gray-400">Learn how to follow expert traders and copy their strategies.</p>
              </div>
            </div>
          </div>
        );
      case 'Market Analysis':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Daily market analysis and insights from our expert team.</p>
            <div className="space-y-6">
              {[1, 2, 3].map((i) => (
                <div key={i} className="p-6 bg-white/5 rounded-2xl border border-white/10 flex flex-col md:flex-row gap-6">
                  <div className="w-full md:w-48 h-32 bg-white/10 rounded-xl flex-shrink-0 animate-pulse" />
                  <div>
                    <div className="text-blue-500 text-xs font-bold uppercase tracking-widest mb-2">Forex Market</div>
                    <h3 className="text-xl font-bold mb-2 text-white">EUR/USD Technical Analysis: Key Levels to Watch</h3>
                    <p className="text-gray-400 mb-4">An in-depth look at the current technical setup for EUR/USD, including major support and resistance zones.</p>
                    <span className="text-xs text-gray-500">Published 2 hours ago</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        );
      case 'Trading Signals':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Real-time trading signals generated by our proprietary algorithms and expert analysts.</p>
            <div className="bg-white/5 rounded-2xl border border-white/10 overflow-hidden">
              <table className="w-full text-left text-sm">
                <thead className="bg-white/5 text-gray-400">
                  <tr>
                    <th className="px-6 py-4 font-medium">Asset</th>
                    <th className="px-6 py-4 font-medium">Signal</th>
                    <th className="px-6 py-4 font-medium">Entry Price</th>
                    <th className="px-6 py-4 font-medium">Timeframe</th>
                    <th className="px-6 py-4 font-medium">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  <tr className="hover:bg-white/[0.02]">
                    <td className="px-6 py-4 font-bold text-white">EUR/USD</td>
                    <td className="px-6 py-4 text-emerald-500 font-bold">BUY</td>
                    <td className="px-6 py-4 text-gray-300">1.0845</td>
                    <td className="px-6 py-4 text-gray-400">15m</td>
                    <td className="px-6 py-4"><span className="px-2 py-1 bg-blue-500/20 text-blue-400 rounded text-xs font-bold">ACTIVE</span></td>
                  </tr>
                  <tr className="hover:bg-white/[0.02]">
                    <td className="px-6 py-4 font-bold text-white">BTC/USD</td>
                    <td className="px-6 py-4 text-rose-500 font-bold">SELL</td>
                    <td className="px-6 py-4 text-gray-300">51,240.00</td>
                    <td className="px-6 py-4 text-gray-400">1h</td>
                    <td className="px-6 py-4"><span className="px-2 py-1 bg-blue-500/20 text-blue-400 rounded text-xs font-bold">ACTIVE</span></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        );
      case 'Education Hub':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Master the markets with our comprehensive learning materials.</p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <div className="w-12 h-12 bg-blue-500/20 rounded-xl flex items-center justify-center mb-4">
                  <span className="text-blue-500 font-bold text-xl">1</span>
                </div>
                <h3 className="text-xl font-bold mb-2 text-white">Beginner Course</h3>
                <p className="text-gray-400 mb-4">Learn the fundamentals of trading and platform navigation.</p>
                <button className="text-blue-400 font-bold hover:text-blue-300">Start Learning →</button>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <div className="w-12 h-12 bg-emerald-500/20 rounded-xl flex items-center justify-center mb-4">
                  <span className="text-emerald-500 font-bold text-xl">2</span>
                </div>
                <h3 className="text-xl font-bold mb-2 text-white">Advanced Strategies</h3>
                <p className="text-gray-400 mb-4">Deep dive into technical analysis and complex trading strategies.</p>
                <button className="text-emerald-400 font-bold hover:text-emerald-300">Start Learning →</button>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <div className="w-12 h-12 bg-purple-500/20 rounded-xl flex items-center justify-center mb-4">
                  <span className="text-purple-500 font-bold text-xl">3</span>
                </div>
                <h3 className="text-xl font-bold mb-2 text-white">Risk Management</h3>
                <p className="text-gray-400 mb-4">Protect your capital and maximize your long-term profitability.</p>
                <button className="text-purple-400 font-bold hover:text-purple-300">Start Learning →</button>
              </div>
            </div>
          </div>
        );
      case 'Tournaments':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Compete with traders worldwide for massive prize pools.</p>
            <div className="p-8 bg-gradient-to-br from-blue-600/20 to-indigo-600/20 rounded-3xl border border-blue-500/30 relative overflow-hidden">
              <div className="absolute top-0 right-0 p-8 opacity-20">
                <Target size={120} />
              </div>
              <div className="relative z-10">
                <span className="px-3 py-1 bg-blue-500 text-white text-xs font-bold rounded-full uppercase tracking-widest mb-4 inline-block">Active Now</span>
                <h3 className="text-3xl font-black mb-2 text-white">Weekly Sprint Tournament</h3>
                <p className="text-gray-300 mb-6 max-w-md">Trade your way to the top of the leaderboard and win a share of the $50,000 prize pool.</p>
                <div className="flex gap-8 mb-8">
                  <div>
                    <div className="text-xs text-gray-400 uppercase tracking-widest mb-1">Prize Pool</div>
                    <div className="text-2xl font-bold text-emerald-400">$50,000</div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-400 uppercase tracking-widest mb-1">Entry Fee</div>
                    <div className="text-2xl font-bold text-white">$10</div>
                  </div>
                  <div>
                    <div className="text-xs text-gray-400 uppercase tracking-widest mb-1">Ends In</div>
                    <div className="text-2xl font-bold text-white">2d 14h</div>
                  </div>
                </div>
                <button className="px-8 py-3 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl transition-colors">Join Tournament</button>
              </div>
            </div>
          </div>
        );
      case 'Affiliate Program':
        return (
          <div className="space-y-12">
            <div className="relative p-10 bg-gradient-to-br from-blue-600/10 to-purple-600/10 rounded-[40px] border border-white/10 overflow-hidden">
              <div className="absolute -top-24 -right-24 w-64 h-64 bg-blue-500/20 blur-[100px] rounded-full" />
              <div className="relative z-10 max-w-2xl">
                <h3 className="text-4xl font-black mb-4 text-white">Become an Onyx Partner</h3>
                <p className="text-gray-400 text-lg mb-8">Join the world's most lucrative affiliate program in the trading industry. Earn high commissions by introducing traders to our premium platform.</p>
                <div className="flex flex-wrap gap-4">
                  <button className="px-8 py-4 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-2xl transition-all shadow-lg shadow-blue-600/20 active:scale-95">Apply Now</button>
                  <button className="px-8 py-4 bg-white/5 hover:bg-white/10 text-white font-bold rounded-2xl border border-white/10 transition-all active:scale-95">Partner Portal</button>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="p-8 bg-white/5 rounded-3xl border border-white/10 hover:border-blue-500/30 transition-colors group">
                <div className="w-14 h-14 bg-blue-500/10 rounded-2xl flex items-center justify-center text-blue-500 mb-6 group-hover:scale-110 transition-transform">
                  <Activity size={28} />
                </div>
                <h4 className="text-xl font-bold mb-2 text-white">High Conversion</h4>
                <p className="text-gray-400 text-sm leading-relaxed">Our optimized landing pages and premium brand reputation ensure the highest conversion rates in the market.</p>
              </div>
              <div className="p-8 bg-white/5 rounded-3xl border border-white/10 hover:border-emerald-500/30 transition-colors group">
                <div className="w-14 h-14 bg-emerald-500/10 rounded-2xl flex items-center justify-center text-emerald-500 mb-6 group-hover:scale-110 transition-transform">
                  <CreditCard size={28} />
                </div>
                <h4 className="text-xl font-bold mb-2 text-white">Instant Payouts</h4>
                <p className="text-gray-400 text-sm leading-relaxed">Withdraw your earnings daily. We support multiple payment methods including Crypto, Bank, and E-wallets.</p>
              </div>
              <div className="p-8 bg-white/5 rounded-3xl border border-white/10 hover:border-purple-500/30 transition-colors group">
                <div className="w-14 h-14 bg-purple-500/10 rounded-2xl flex items-center justify-center text-purple-500 mb-6 group-hover:scale-110 transition-transform">
                  <Target size={28} />
                </div>
                <h4 className="text-xl font-bold mb-2 text-white">Advanced Tracking</h4>
                <p className="text-gray-400 text-sm leading-relaxed">Real-time dashboard to track your clicks, registrations, and commissions with surgical precision.</p>
              </div>
            </div>

            <div className="space-y-6">
              <h3 className="text-2xl font-bold text-white flex items-center gap-3">
                <div className="w-1 h-8 bg-blue-500 rounded-full" />
                Commission Structure
              </h3>
              <div className="bg-white/5 rounded-[32px] border border-white/10 overflow-hidden">
                <div className="grid grid-cols-1 md:grid-cols-3 divide-y md:divide-y-0 md:divide-x divide-white/10">
                  <div className="p-8 text-center space-y-2">
                    <div className="text-xs font-bold text-gray-500 uppercase tracking-widest">Standard</div>
                    <div className="text-4xl font-black text-white">40%</div>
                    <div className="text-sm text-gray-400">Revenue Share</div>
                    <div className="pt-4 text-xs text-blue-400 font-bold">0 - 50 Active Traders</div>
                  </div>
                  <div className="p-8 text-center space-y-2 bg-blue-500/5">
                    <div className="text-xs font-bold text-blue-500 uppercase tracking-widest">Premium</div>
                    <div className="text-4xl font-black text-white">50%</div>
                    <div className="text-sm text-gray-400">Revenue Share</div>
                    <div className="pt-4 text-xs text-blue-400 font-bold">51 - 200 Active Traders</div>
                  </div>
                  <div className="p-8 text-center space-y-2">
                    <div className="text-xs font-bold text-purple-500 uppercase tracking-widest">VIP</div>
                    <div className="text-4xl font-black text-white">60%</div>
                    <div className="text-sm text-gray-400">Revenue Share</div>
                    <div className="pt-4 text-xs text-blue-400 font-bold">200+ Active Traders</div>
                  </div>
                </div>
              </div>
            </div>

            <div className="space-y-6">
              <h3 className="text-2xl font-bold text-white flex items-center gap-3">
                <div className="w-1 h-8 bg-emerald-500 rounded-full" />
                How to Start
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                {[
                  { step: '01', title: 'Register', desc: 'Sign up for a partner account in seconds.' },
                  { step: '02', title: 'Promote', desc: 'Use your unique link to invite traders.' },
                  { step: '03', title: 'Track', desc: 'Monitor performance in your dashboard.' },
                  { step: '04', title: 'Earn', desc: 'Receive daily payouts of your profit.' }
                ].map((item, idx) => (
                  <div key={idx} className="p-6 bg-white/5 rounded-2xl border border-white/10 relative">
                    <div className="text-3xl font-black text-white/10 absolute top-4 right-4">{item.step}</div>
                    <h4 className="font-bold text-white mb-2">{item.title}</h4>
                    <p className="text-gray-500 text-xs leading-relaxed">{item.desc}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="p-10 bg-white/5 rounded-[40px] border border-white/10 text-center space-y-6">
              <h3 className="text-3xl font-bold text-white">Ready to scale your income?</h3>
              <p className="text-gray-400 max-w-xl mx-auto">Our dedicated affiliate managers are ready to help you optimize your campaigns and maximize your revenue.</p>
              <button className="px-12 py-5 bg-white text-black font-black rounded-2xl hover:bg-gray-200 transition-all active:scale-95 uppercase tracking-widest text-sm">Get Started Today</button>
            </div>
          </div>
        );
      case 'Security':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Your security is our top priority. Learn about our industry-leading protection measures.</p>
            <div className="space-y-6">
              <div className="flex gap-4 p-6 bg-white/5 rounded-2xl border border-white/10">
                <Shield className="text-blue-500 shrink-0" size={32} />
                <div>
                  <h3 className="text-xl font-bold mb-2 text-white">Military-Grade Encryption</h3>
                  <p className="text-gray-400">All data transmissions are protected by 256-bit SSL encryption, ensuring your personal and financial information remains completely secure.</p>
                </div>
              </div>
              <div className="flex gap-4 p-6 bg-white/5 rounded-2xl border border-white/10">
                <Lock className="text-emerald-500 shrink-0" size={32} />
                <div>
                  <h3 className="text-xl font-bold mb-2 text-white">Two-Factor Authentication (2FA)</h3>
                  <p className="text-gray-400">Add an extra layer of security to your account with mandatory 2FA for all withdrawals and sensitive account changes.</p>
                </div>
              </div>
              <div className="flex gap-4 p-6 bg-white/5 rounded-2xl border border-white/10">
                <CheckCircle2 className="text-indigo-500 shrink-0" size={32} />
                <div>
                  <h3 className="text-xl font-bold mb-2 text-white">Segregated Accounts</h3>
                  <p className="text-gray-400">Client funds are kept entirely separate from company operational funds in top-tier global banking institutions.</p>
                </div>
              </div>
            </div>
          </div>
        );
      case 'Features':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Everything you need to master the financial markets in one powerful platform.</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">Instant Execution</h3>
                <p className="text-gray-400">Trades are executed in less than 5ms, ensuring you get the best possible price every time.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">Secure Platform</h3>
                <p className="text-gray-400">Military-grade encryption and segregated accounts to keep your funds and data safe.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">Advanced Charts</h3>
                <p className="text-gray-400">Professional technical indicators and drawing tools built directly into the terminal.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">Global Markets</h3>
                <p className="text-gray-400">Trade Forex, Crypto, Stocks, and Commodities from a single unified interface.</p>
              </div>
            </div>
          </div>
        );
      case 'How it works':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Start Trading in 3 Simple Steps.</p>
            <div className="space-y-6">
              <div className="flex gap-4 p-6 bg-white/5 rounded-2xl border border-white/10">
                <div className="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center text-white font-black text-xl shrink-0">1</div>
                <div>
                  <h3 className="text-xl font-bold mb-2 text-white">Create Account</h3>
                  <p className="text-gray-400">Sign up for a free account in less than 30 seconds. No credit card required to start.</p>
                </div>
              </div>
              <div className="flex gap-4 p-6 bg-white/5 rounded-2xl border border-white/10">
                <div className="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center text-white font-black text-xl shrink-0">2</div>
                <div>
                  <h3 className="text-xl font-bold mb-2 text-white">Make Deposit</h3>
                  <p className="text-gray-400">Fund your account with over 20+ payment methods including Crypto, Cards, and E-wallets.</p>
                </div>
              </div>
              <div className="flex gap-4 p-6 bg-white/5 rounded-2xl border border-white/10">
                <div className="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center text-white font-black text-xl shrink-0">3</div>
                <div>
                  <h3 className="text-xl font-bold mb-2 text-white">Start Trading</h3>
                  <p className="text-gray-400">Choose your asset, set your investment, and start trading with up to 98% payout.</p>
                </div>
              </div>
            </div>
          </div>
        );
      case 'Live Trades':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Real-time Trading Results from our community.</p>
            <div className="bg-white/5 rounded-2xl border border-white/10 overflow-hidden">
              <table className="w-full text-left text-sm">
                <thead className="bg-white/5 text-gray-400">
                  <tr>
                    <th className="px-6 py-4 font-medium">Asset</th>
                    <th className="px-6 py-4 font-medium">Time</th>
                    <th className="px-6 py-4 font-medium">Investment</th>
                    <th className="px-6 py-4 font-medium text-right">Profit</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  <tr className="hover:bg-white/[0.02]">
                    <td className="px-6 py-4 font-bold text-white">EUR/USD</td>
                    <td className="px-6 py-4 text-gray-500 font-mono">18:45:12</td>
                    <td className="px-6 py-4 text-gray-300">$1,200</td>
                    <td className="px-6 py-4 text-right font-bold text-emerald-500">+$1,104</td>
                  </tr>
                  <tr className="hover:bg-white/[0.02]">
                    <td className="px-6 py-4 font-bold text-white">BTC/USD</td>
                    <td className="px-6 py-4 text-gray-500 font-mono">18:44:58</td>
                    <td className="px-6 py-4 text-gray-300">$500</td>
                    <td className="px-6 py-4 text-right font-bold text-emerald-500">+$450</td>
                  </tr>
                  <tr className="hover:bg-white/[0.02]">
                    <td className="px-6 py-4 font-bold text-white">ETH/USD</td>
                    <td className="px-6 py-4 text-gray-500 font-mono">18:44:15</td>
                    <td className="px-6 py-4 text-gray-300">$100</td>
                    <td className="px-6 py-4 text-right font-bold text-rose-500">-$100</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        );
      case 'FAQ':
        return (
          <div className="space-y-8">
            <p className="text-gray-400 text-lg">Find answers to the most common questions about ONYX OPTION.</p>
            <div className="space-y-4">
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">What is the minimum deposit?</h3>
                <p className="text-gray-400">The minimum deposit to start trading on a live account is only $10. However, you can start practicing on our demo account with $10,000 in virtual funds for free.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">How long do withdrawals take?</h3>
                <p className="text-gray-400">Withdrawals are typically processed within 24 hours. Depending on your payment method, funds usually arrive in your account within 1-3 business days.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">Is ONYX OPTION regulated?</h3>
                <p className="text-gray-400">Yes, ONYX OPTION follows strict international financial regulations and keeps all client funds in segregated accounts with top-tier global banks.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                <h3 className="text-xl font-bold mb-2 text-white">Can I trade on my mobile device?</h3>
                <p className="text-gray-400">Absolutely! We offer powerful mobile applications for both iOS and Android, providing the full trading experience on the go.</p>
              </div>
            </div>
          </div>
        );
      case 'Privacy Policy':
      case 'Terms of Service':
      case 'Risk Disclosure':
      case 'AML Policy':
      case 'Cookie Policy':
        return (
          <div className="space-y-6 text-gray-400 leading-relaxed">
            <p>Last updated: March 2024</p>
            <h3 className="text-xl font-bold text-white mt-8 mb-4">1. Introduction</h3>
            <p>This document constitutes a legally binding agreement between you and ONYX OPTION. By accessing or using our platform, you acknowledge that you have read, understood, and agree to be bound by these terms.</p>
            
            <h3 className="text-xl font-bold text-white mt-8 mb-4">2. General Provisions</h3>
            <p>The services provided by ONYX OPTION are intended for users who are at least 18 years of age. We reserve the right to request proof of age and identity at any time.</p>
            
            <h3 className="text-xl font-bold text-white mt-8 mb-4">3. User Responsibilities</h3>
            <p>Users are solely responsible for maintaining the confidentiality of their account credentials and for all activities that occur under their account. Any unauthorized use must be reported immediately.</p>
            
            <h3 className="text-xl font-bold text-white mt-8 mb-4">4. Compliance</h3>
            <p>We strictly adhere to international regulatory standards, including Anti-Money Laundering (AML) and Know Your Customer (KYC) protocols. Users must provide accurate information and cooperate with verification requests.</p>
            
            <div className="mt-12 p-6 bg-white/5 rounded-xl border border-white/10">
              <p className="text-sm">For the complete, legally binding version of this document, please download the PDF version from our Legal archive.</p>
            </div>
          </div>
        );
      default:
        return (
          <div className="text-center py-20">
            <p className="text-gray-400 text-lg">Content for {title} is currently being updated.</p>
          </div>
        );
    }
  };

  return (
    <div className="min-h-[100dvh] bg-[#050505] text-white font-sans selection:bg-blue-500/30">
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#050505]/80 backdrop-blur-xl border-b border-white/5">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center h-20 gap-4">
            <button 
              onClick={onBack}
              className="w-10 h-10 rounded-full bg-white/5 flex items-center justify-center hover:bg-white/10 transition-colors"
            >
              <ChevronLeft size={24} />
            </button>
            <h1 className="text-xl font-bold">{title}</h1>
          </div>
        </div>
      </nav>

      <main className="pt-32 pb-20 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-12">
          <h2 className="text-4xl md:text-5xl font-black mb-4">{title}</h2>
          <div className="w-20 h-1 bg-blue-500 rounded-full"></div>
        </div>
        
        {renderContent()}
      </main>
    </div>
  );
}
